spring.application.name=td5
spring.datasource.url=jdbc:postgresql://localhost:5432/td5_restaurant
spring.datasource.username=postgres
spring.datasource.password=Kokoo271107;

spring.datasource.driver-class-name=org.postgresql.Driver